<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Octothorp</Authors>
    <Company />
    <RepositoryUrl>https://github.com/jh12/Imget.Shared</RepositoryUrl>
  </PropertyGroup>
  
</Project>
